include ../Makefile-example

.PHONY: run
run:
	@python main.py --modelstore-in aws
	@python main.py --modelstore-in azure
	@python main.py --modelstore-in gcloud
	@python main.py --modelstore-in filesystem
	@python main.py --modelstore-in hosted
