name: Integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        storage-type: ["filesystem"]
        #, "aws", "gcp", "azure"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        cd workflows/storage-types
        make setup
    - name: Run integration script
      run: |
        cd workflows/storage-types
        python main.py --modelstore-in ${{ matrix.storage-type }}
